services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
    ports:
      - 80:80
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    networks:
      - express-redis
      - react-express

  redis:
    restart: always
    image: redis
    volumes:
      - todo-redis-data:/data
    networks:
      - express-redis
    expose:
      - 6379

networks:
  react-express:
  express-redis:

volumes:
  todo-redis-data:
